name: Publish Docker Image
on:
  release:
    types: [published, edited]

jobs:
  push_to_registries:
    name: Push to registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set Environment Variables
      run: |
        echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2.3.0
      with:
        tags: |
          destis/stress-service/stress-service:latest
          destis/stress-service:${{ env.GIT_REF }}
        push: true
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2.3.0
      with:
        tags: |
          docker.pkg.github.com/idestis/stress-service/stress-service:${{ env.GIT_REF }}
        push: true
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}