name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push to registry
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: destis/stress-service
        tag_with_ref: true
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: idestis/stress-service
        tag_with_ref: true
        
